services:
  server:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: unless-stopped
    depends_on:
      restore:
        condition: service_completed_successfully
    environment:
      UID: '$UID'
      GID: '$GID'
      EULA: true
      GUI: false
      VERSION: 1.20.5
      TYPE: FABRIC
      MAX_MEMORY: 8g
      DIFFICULTY: hard
      ALLOW_FLIGHT: true
      MODS_FILE: /extras/.mods
      SERVER_NAME: moonfall
      MOTD: drew's tiktok house
      ICON: https://i.imgur.com/EiYG8C4.png
    volumes:
      - ./data:/data
      - ./extras:/extras

  router:
    image: itzg/mc-router
    depends_on:
      - server
    ports:
      - 25565:25565
    restart: unless-stopped
    command: --mapping=${HOST}=server:25565

  restore:
    image: itzg/mc-backup
    restart: no
    entrypoint: restore-tar-backup
    environment:
      UID: '$UID'
      GID: '$GID'
    volumes:
      - ./data:/data
      - ./backups:/backups:ro

  backups:
    image: itzg/mc-backup
    depends_on:
      server:
        condition: service_healthy
    restart: unless-stopped
    environment:
      INITIAL_DELAY: 0
      RCON_HOST: server
      BACKUP_INTERVAL: 3h
      PRUNE_BACKUPS_DAYS: 2
    volumes:
      - ./data:/data:ro
      - ./backups:/backups
